# Generated by Django 2.1 on 2018-12-16 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20181216_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(choices=[('terrible', 'Ужасно'), ('bad', 'Плохо'), ('ok', 'Нормально'), ('good', 'Хорошо'), ('fine', 'Отлично')], max_length=20, verbose_name='Оценка')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Article', verbose_name='Статья')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.User', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
    ]
