# Generated by Django 2.1 on 2018-12-17 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20181217_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratting',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rattings', to='webapp.Article', verbose_name='Статья'),
        ),
    ]
